product_models_view_serializers
online-furniture-store/online_furniture_store_backend pull request #22
Opened 2023-06-04 01:29 UTC by Markello93

Прописал модели, вьюсеты, сериализаторы для сущностей товаров кроме корзины.
В конфиге подправлял пути для сохранения media, возможно надо оставить руты как были, но изменить тогда сам путь сохранения изображения. Немного не разобрался.

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    color = models.CharField(verbose_name='Цвет')
Для совместимости с бд лучше указать _max_length_

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    article = models.IntegerField(verbose_name='Артикул', null=False, unique=True)
Здесь лучше использовать другой класс _PositiveIntegerField_

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    weight = models.IntegerField(verbose_name='Вес, кг', null=False)
Здесь хватит и _PositiveSmallIntegerField_

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    color = models.CharField(verbose_name='Цвет')
Может сделать ещё одну сущность для цвета или может сделать выбор цветов?

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    material = models.ManyToManyField(Materials)
Укажи _related_name_ будет проще писать запросы для выборки товаров по цветам

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    brand = models.CharField(verbose_name='Бренд', null=True)
Здесь тоже не хватает _max_length_

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    weight = models.IntegerField(verbose_name='Вес, кг', null=False)
_null=False_ - это значение по умолчанию
Зачем ещё раз его прописывать?)

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    brand = models.CharField(verbose_name='Бренд', null=True)
Если значение может быть null, то стоит отменить проверку на не пустое значение
Добавь blank=True

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    warranty = models.IntegerField(verbose_name='Гарантия , лет', null=True)
Здесь также

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    category = models.ForeignKey(Categories, verbose_name='Категория', on_delete=models.CASCADE, null=False)
Здесь на хватает _related_name_

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    class Meta:
Нужна сортировка, нужно узнать у ПМ по какому принципу это сделать

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    user = models.ForeignKey(User, verbose_name='Пользователь', related_name='fav_user', on_delete=models.CASCADE)
В related_name удобней использовать имя класса, ведь запрос будет строиться из модели пользователя Users и множественное число, потому что это будет queryset

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/models.py
> +    product = models.ForeignKey(Product, verbose_name='Товар', related_name='fav_product', on_delete=models.CASCADE)
И здесь также

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/serializers.py
> +class Base64ImageField(serializers.ImageField):
Почему не использовал библиотеку _drf_extra_fields_

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/serializers.py
> +        fields = ['name', 'slug']
Почему не использовать кортеж?

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/serializers.py
> +        fields = ['name']
И здесь кортеж

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/serializers.py
> +
Почему здесь пустая строка?

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/serializers.py
> +
Почему здесь пустая строка?

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/serializers.py
> +    def is_item_related(self, product, model):
А чем вызвано вынесение этого функционала в отдельную функцию?

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/views.py
> +class CategoriesViewSet(ModelViewSet):
Может здесь использовать ReadOnlyModelViewSet

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/views.py
> +class MaterialsViewSet(ModelViewSet):
Здесь тоже

2023-06-08 15:08 UTC, SaPer663 commented on apps/product/views.py
> +        elif request.method == 'DELETE':
else не нужен, если не пройдёт в блок POST, то выполнится код ниже

2023-06-08 17:03 UTC, Markello93 commented on apps/product/models.py
> +    color = models.CharField(verbose_name='Цвет')
У нас есть понимание какая максимальная длина будет? В фич листе не нашел.

2023-06-08 17:04 UTC, Markello93 commented on apps/product/models.py
> +    article = models.IntegerField(verbose_name='Артикул', null=False, unique=True)
Согласен, по примеру данных в БД ориентируемся на то, что артикул не может быть смешанный - буквы, цифры, символы(Charfield), только цифры?

2023-06-08 17:05 UTC, Markello93 commented on apps/product/models.py
> +    weight = models.IntegerField(verbose_name='Вес, кг', null=False)
Согласен, поправил.

2023-06-08 17:06 UTC, Markello93 commented on apps/product/models.py
> +    color = models.CharField(verbose_name='Цвет')
Если количество цветов ограничено небольшим количеством то да, можно второй вариант. Я больше склоняюсь к тому, чтобы сделать отдельную сущность.

2023-06-08 17:09 UTC, Markello93 commented on apps/product/models.py
> +    material = models.ManyToManyField(Materials)
Как думаешь имеет смысл только для цвета указать?

2023-06-08 17:09 UTC, Markello93 commented on apps/product/serializers.py
> +
Поправил.

2023-06-08 17:10 UTC, Markello93 commented on apps/product/serializers.py
> +    def is_item_related(self, product, model):
Если ты про функции , def is_item_related(self, product, model) и  def get_is_favorited(self, product) для одного действия, я разнес их на 2 с запасом , что тут будет еще будет прописана логика под корзину. Могу пока сделать одну функцию.

2023-06-08 17:10 UTC, Markello93 commented on apps/product/views.py
> +class CategoriesViewSet(ModelViewSet):
Согласен, сделал.

2023-06-08 17:10 UTC, Markello93 commented on apps/product/views.py
> +        elif request.method == 'DELETE':
Исправил.

2023-06-08 17:12 UTC, SaPer663 commented on apps/product/models.py
> +    material = models.ManyToManyField(Materials)
О, здесь не правильно указал строку, к которой относиться коммент
Я здесь про поле meterial

2023-06-08 17:14 UTC, SaPer663 commented on apps/product/models.py
> +    color = models.CharField(verbose_name='Цвет')
Да, я про неё тоже подумал, ведь цветов может быть много и они могут добавляться со временем

2023-06-08 17:20 UTC, SaPer663 commented on apps/product/models.py
> +    article = models.IntegerField(verbose_name='Артикул', null=False, unique=True)
Тут коммент направлен на исправление твоего выбора в пользу просто integer. А нас ведь артикль не может быть отрицательным числом.
Да, и судя по базе у нас просто числа

2023-06-08 17:22 UTC, SaPer663 commented on apps/product/models.py
> +    color = models.CharField(verbose_name='Цвет')
Ну представь, какое самое большое число  может быть)

2023-06-08 17:27 UTC, SaPer663 commented on apps/product/serializers.py
> +    def is_item_related(self, product, model):
Если у тебя есть задумка применять её ещё раз, то всё нормально)
Я поэтому уточнил

2023-06-08 17:49 UTC, SaPer663 commented on apps/product/admin.py
> +    empty_value_display = '-пусто-'
Марк, это лучше вынести в константу

2023-06-08 17:49 UTC, SaPer663 commented on config/api_router.py
> +router.register(r'product', ProductViewSet, basename='product')
Лучше множественное число сделать

2023-06-08 17:49 UTC, SaPer663 commented on config/api_router.py
> +router.register(r'product', ProductViewSet, basename='product')
И прийти к единому стилю написания, а то у тебя только в одной строке явное указание сырой строки

2023-06-09 05:19 UTC, SaPer663 requested changes

2023-06-09 05:19 UTC, SaPer663 commented on apps/product/models.py
> +    material = models.ManyToManyField(Materials, related_name='material')
related_name надо переименовать в название модели во множественном числе products

2023-06-09 05:19 UTC, SaPer663 commented on apps/product/models.py
> +        Categories, verbose_name='Категория', on_delete=models.CASCADE, related_name='category', null=False
related_name надо переименовать в название модели во множественном числе products
и можно удалить значение по умолчанию null=False

2023-06-09 05:19 UTC, SaPer663 commented on apps/product/serializers.py
>  class Base64ImageField(serializers.ImageField):
Тебе не делали замечания про кастомное поле для картинок в ЯП?
Лучше использовать стороннюю либу, которая уже проверенна и протестирована

2023-06-09 05:19 UTC, SaPer663 commented on apps/product/models.py
> +    color = models.ForeignKey(Colors, verbose_name='Цвет', on_delete=models.CASCADE, related_name='color')
related_name надо переименовать в название модели во множественном числе products

2023-06-09 05:19 UTC, SaPer663 commented on apps/product/views.py
>      http_method_names = ['get']
Это атрибут уже не нужен, у тебя класс родитель реализует только этот метод

2023-06-09 05:19 UTC, SaPer663 commented on apps/product/views.py
>      http_method_names = ['get']
Это атрибут уже не нужен, у тебя класс родитель реализует только этот метод

2023-06-09 05:19 UTC, SaPer663 commented on apps/product/views.py
> +    http_method_names = ['get']
Это атрибут уже не нужен, у тебя класс родитель реализует только этот метод

2023-06-09 05:19 UTC, SaPer663 commented on config/api_router.py
> +router.register('colors', ProductViewSet, basename='colors')
Торопишься)
Вьюсет не тот указал)

2023-06-09 05:19 UTC, SaPer663 commented on apps/product/models.py
>      description = models.CharField(verbose_name='Описание', null=False)
Надо указать атрибут max_lenght и можно удалить значение по умолчанию null=False

2023-06-09 05:19 UTC, SaPer663 commented on apps/product/models.py
>      price = models.DecimalField(verbose_name='Цена', null=False, max_digits=10, decimal_places=2)
Можно удалить значение по умолчанию null=False

2023-06-09 05:19 UTC, SaPer663 commented on apps/product/models.py
>      brand = models.CharField(verbose_name='Бренд', null=True)
Надо указать атрибут max_lenght

2023-06-09 05:19 UTC, SaPer663 commented on apps/product/models.py
> +    weight = models.PositiveSmallIntegerField(verbose_name='Вес, кг', validators=[MaxValueValidator(500)], null=False)
Можно удалить значение по умолчанию null=False

2023-06-09 14:51 UTC, SaPer663 commented on apps/product/models.py
> +    material = models.ManyToManyField(Material, related_name='materials')
related_name лучше образовывать от названия модели, в которой определяется поле и во мн. ч.
Здесь это products

2023-06-09 14:51 UTC, SaPer663 commented on apps/product/models.py
> +        Category, verbose_name='Категория', on_delete=models.CASCADE, related_name='categories'
related_name лучше образовывать от названия модели, в которой определяется поле и во мн. ч.
Здесь это products

2023-06-09 16:05 UTC, merged