Feat/users
online-furniture-store/online_furniture_store_backend pull request #30
Opened 2023-06-08 08:39 UTC by Artek22

Регистрация юзера по номеру телефона. Суперюзера, добавление юзера через админку и самостоятельная регистрация через localhost:8000/auth/users/

2023-06-08 13:45 UTC, SaPer663 commented on apps/users/admin.py
> +        (None, {'fields': ('phone', 'password')}),
Здесь нужно все поля прописать, что указаны в фич-листе:
имя - first_name;
фамилия - last_name;
телефон - phone;
почта - email;
дата рождения - birthday;
пол - gender;

2023-06-08 13:45 UTC, SaPer663 commented on apps/users/admin.py
> +    list_display = ['phone', 'username', 'is_superuser']
username - такого поля у нас нет в ТЗ
Сюда стоит вписать все обязательные поля пользователя, а is_superuser можно в фильтры включить

2023-06-08 13:45 UTC, SaPer663 commented on apps/users/admin.py
> +    search_fields = ['username']
Поиск по телефону сделать или по фамилии или вместе

2023-06-08 13:45 UTC, SaPer663 commented on apps/users/apps.py
>      def ready(self):
Это неиспользуемый метод, его надо удалить, чтобы не сбивал с толку

2023-06-08 13:45 UTC, SaPer663 commented on apps/users/models.py
>      # First and last name do not cover name patterns around the globe
Лучше удалить комментарии, если они не несут никакую информацию.

2023-06-08 13:45 UTC, SaPer663 commented on apps/users/models.py
> +    # name = CharField(_('Name of User'), blank=True, max_length=255)
Здесь также

2023-06-08 13:45 UTC, SaPer663 commented on apps/users/models.py
> +    first_name = CharField('Имя', max_length=50, blank=True)
В фич-листе длина имени указана не более 20 символов

2023-06-08 13:45 UTC, SaPer663 commented on apps/users/models.py
> +    username = CharField('Имя пользователя', max_length=50, blank=True)
Это поле нам не нужно

2023-06-08 13:45 UTC, SaPer663 commented on config/settings/base.py
> +# MIGRATION_MODULES = {'sites': 'online_furniture_store_backend.contrib.sites.migrations'}
Надо подтянуть изменения с dev ветки, там уже этого нет в настройках

2023-06-08 13:45 UTC, SaPer663 commented on config/settings/base.py
> +                # 'online_furniture_store_backend.users.context_processors.allauth_settings',
Здесь также

2023-06-08 13:45 UTC, SaPer663 commented on config/urls.py
> +from django.urls import include, path, re_path
Может это будет излишним применять в простом шаблоне регулярку?

2023-06-08 13:45 UTC, SaPer663 commented on config/urls.py
> +    re_path(r'^auth/', include('djoser.urls.authtoken')),
Это надо обсудить

2023-06-08 15:54 UTC, Markello93 commented on apps/users/apps.py
>      def ready(self):
ты про def ready?
Я вот тоже не понял его, я так понимаю можно создать файл singnals, где модернизируются какие то джанговские отклики?

2023-06-08 16:47 UTC, Markello93 commented on apps/users/admin.py
> +        (None, {'fields': ('phone', 'password')}),
Ты уже задавал это вопрос в excel файлике. Зачем нам пол вообще? Системы рекомендаций, которая как то завязана на это у нас нет, форума , где будет отображаться тоже.

2023-06-08 17:01 UTC, Markello93 commented on apps/users/models.py
> +    REQUIRED_FIELDS = ['email']
А зачем нам  REQUIRED_FIELDS = ['email']?

2023-06-08 17:01 UTC, Markello93 commented on apps/users/admin.py
> +    list_display = ['phone', 'username', 'is_superuser']
Не стоит ли нам дописать свои Permissions? 
Допустим в дальнейшем продукты только админ и там используем что-то вроде IsAdminOrReadOnly?

2023-06-08 18:11 UTC, SaPer663 requested changes

2023-06-08 18:11 UTC, SaPer663 commented on apps/users/admin.py
> +        (None, {'fields': ('phone', 'password')}),
Да, я написал на основании уже имеющихся данных, потом можем поправить

2023-06-08 18:11 UTC, SaPer663 commented on apps/users/admin.py
> +    list_display = ['phone', 'username', 'is_superuser']
Да, но это не относиться к админке)

2023-06-08 18:11 UTC, SaPer663 commented on apps/users/apps.py
>      def ready(self):
Да, сигналы не рекомендуют использовать, только в редких случаях

2023-06-09 08:25 UTC, Artek22 commented on apps/users/admin.py
> +        (None, {'fields': ('phone', 'password')}),
У нас при регистрации должен запрашиваться только телефон, все остальные поля не в филдсете должны быть, а в модели скорее

2023-06-09 08:38 UTC, Artek22 commented on apps/users/models.py
> +    first_name = CharField('Имя', max_length=50, blank=True)
Ну это не фича все-таки. Длина поля определяется бэком, если она не "от", а "до". Тут можно и 255 указать, это не будет несоответствием ТЗ.

2023-06-09 09:23 UTC, Artek22 commented on config/urls.py
> +    re_path(r'^auth/', include('djoser.urls.authtoken')),
Тут я оставил сет шаблона

2023-06-09 12:02 UTC, SaPer663 commented on apps/users/admin.py
> +        (None, {'fields': ('phone', 'password')}),
Не совсем так, Андрей, list_display - это таблица всех записей
А fieldsets - это отображение деталей каждой записи, а не поля для регистрации

2023-06-09 12:19 UTC, SaPer663 requested changes

2023-06-09 12:19 UTC, SaPer663 commented on apps/users/models.py
> +    date_joined = DateTimeField(default=timezone.now)
Это поле уже есть в классе родителе

2023-06-09 12:19 UTC, SaPer663 commented on apps/users/models.py
>      def get_absolute_url(self) -> str:
Этот метод нам не нужен

2023-06-09 12:19 UTC, SaPer663 commented on apps/users/models.py
> +    gender = CharField('Пол', max_length=10, default=GENDER[0])
Надо реализовать выбор из списка

2023-06-09 12:19 UTC, SaPer663 commented on apps/users/models.py
>      phone = CharField('Телефон', max_length=50, unique=True)
для телефона нужно реализовать валидатор

2023-06-09 12:19 UTC, SaPer663 commented on config/urls.py
> +    path('auth/', include('djoser.urls.authtoken')),
А разве это путь будет участвовать в работе?

2023-06-09 13:00 UTC, Artek22 commented on config/urls.py
> +    path('auth/', include('djoser.urls.authtoken')),
Я из документации брал пример с re_path, поэтому не знаю как иначе прописать. Могу вернуть регулярное выражение

2023-06-09 13:22 UTC, SaPer663 commented on config/urls.py
> +    path('auth/', include('djoser.urls.authtoken')),
Тогда оставляй как есть, это я перемудрил

2023-06-09 14:06 UTC, SaPer663 commented on apps/users/models.py
> +    first_name = CharField('Имя', max_length=50, blank=True)
А зачем создавать поле в таблице с заведомо большим размером, чем будет использоваться

2023-06-11 11:00 UTC, SaPer663 commented on apps/users/models.py
> +    gender = CharField('Пол', max_length=30, choices=GENDER, default=GENDER[0])
Дефолтное значение не соответствует типу поля

2023-06-11 11:00 UTC, SaPer663 commented on apps/users/models.py
> +    first_name = CharField('Имя', max_length=30, blank=True)
Если поле null=False, то вызовется ошибка при создании записи без заполнения этого поля

2023-06-11 11:00 UTC, SaPer663 commented on apps/users/models.py
>      last_name = CharField('Фамилия', max_length=50, blank=True)
Здесь также

2023-06-11 11:00 UTC, SaPer663 commented on apps/users/validators.py
> +    if match(r'^((8|\+7)[\- ]?)?(\(?\d{3}\)?[\- ]?)?[\d\- ]{7}$', value):
Надо реализовать проверку на номера вида +79651234578 и 89856547812, а возвращать значение 9845632145

2023-06-11 11:00 UTC, SaPer663 commented on requirements/base.txt
Почему у тебя поменялись зависимости?
Надо оставить как есть, если что-то добавилось, внеси руками, в том же стиле

2023-06-11 11:42 UTC, Artek22 commented on apps/users/models.py
> +    first_name = CharField('Имя', max_length=30, blank=True)
У меня наоборот, вылетает ошибка при создании записи при null=True. 
`null value in column "first_name" of relation "users_user" violates not-null constraint
`

2023-06-11 13:31 UTC, SaPer663 requested changes

2023-06-11 13:31 UTC, SaPer663 commented on apps/users/models.py
> +    gender = CharField('Пол', max_length=30, choices=GENDER, default=GENDER[0][1])
Андрей, первый элемент кортежа записывается в базу, второй - для отображения применяется

2023-06-11 13:31 UTC, SaPer663 commented on config/urls.py
> +    path('api-token-auth/', views.obtain_auth_token),
Это лишнее, у нас же JWT

2023-06-11 13:31 UTC, SaPer663 commented on config/urls.py
> +    path('auth/', include('djoser.urls.jwt')),
Это мы же договорились за api убрать?

2023-06-11 13:31 UTC, SaPer663 commented on requirements/base.txt
Нет в зависимостях
djoser https://github.com/sunscrapers/djoser
djangorestframework_simplejwt https://github.com/jazzband/djangorestframework-simplejwt

2023-06-11 13:31 UTC, SaPer663 commented on apps/users/validators.py
> +        return str(''.join(correct_value))[-10:]
Будет быстрее работать и по памяти выгоднее сделать через генератор списков.
И срез можно сразу же взять от входящего значения, а не от итогового

2023-06-11 14:21 UTC, Artek22 commented on apps/users/validators.py
> +        return str(''.join(correct_value))[-10:]
А как ты поймешь какой срез брать в случае +7-903-1233232 и 89031233232?

2023-06-11 14:26 UTC, SaPer663 commented on apps/users/validators.py
> +        return str(''.join(correct_value))[-10:]
Да, ты прав, тогда можно применить срез к correct_value, чтобы уменьшить количество итераций

2023-06-11 15:02 UTC, SaPer663 approved these changes

2023-06-12 11:24 UTC, merged