Feat/orders
online-furniture-store/online_furniture_store_backend pull request #40
Opened 2023-06-16 11:09 UTC by KoshelevAleksandr

Модели заказов, сериализаторы, вью, урлы

2023-06-16 11:45 UTC, mikepavlos approved these changes

2023-06-16 13:12 UTC, SaPer663 requested changes

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/models.py
> +        validators=[MinValueValidator(limit_value=0, message='Минимальное количество 1!')]
Здесь спорный лимит. Что будет, если купят весь товар?

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/models.py
> +    cost = models.DecimalField(max_digits=40, decimal_places=2, null=True, blank=True)
Не хватает verbose_name

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/models.py
> +    total_cost = models.DecimalField(max_digits=40, decimal_places=2, null=True, blank=True)
Саш, а почему поле не обязательное?
Не хватает verbose_name

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
> +        method = value
А эта переменная для чего?

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
> +    def validate_name(self, value):
Вся валидация подтянется из модели, это встроенный механизм DRF, не стоит его переопределять.

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
> +    name = serializers.CharField(max_length=20)
А для чего нужно это поле?

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
> +    adres = serializers.CharField(max_length=200)
Саш, исправь опечатку -> address
Для чего переопределяешь поле?
Ты же используешь ModelSerializer

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
> +    phone = serializers.CharField(max_length=20)
И здесь?

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/models.py
> +    # user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='orders',verbose_name='Клиент')
А почему убрал пользователя?

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/models.py
> +class Orders(models.Model):
Сущность одна, поэтому название модели в ед. ч. Order

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/models.py
> +class DeliveryMethod(models.Model):
Может переименовать в тип доставки?

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/models.py
> +    adres = models.CharField(max_length=200, verbose_name='Адрес')
Опечатка в имени переменной address

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/models.py
> +    phone = models.CharField(max_length=12, verbose_name='Телефон')
А здесь не хватает валидатора номеров телефонов

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/models.py
> +        DeliveryMethod, related_name='delivery', verbose_name='Доставка', on_delete=models.PROTECT
А если в магазине перестанет действовать доставка курьером, то мы не сможем удалить тип доставки из модели?

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
> +    type_delivery = serializers.PrimaryKeyRelatedField(queryset=DeliveryMethod.objects.all())
PrimaryKeyRelatedField по умолчанию такой же, его можно не определять

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
> +        fields = ('id', 'adres', 'phone', 'type_delivery', 'created', 'updated')
опечатка address

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
> +        quantity = value
Саш, зачем промежуточная переменная?

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
> +    def validate_quantity(self, value):
У поля есть встроенный валидатор из модели

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
> +    cost = serializers.SerializerMethodField
Не хватает создания экземпляра класса

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
> +        products = value
Для чего эта переменная?

2023-06-16 13:12 UTC, SaPer663 commented on config/api_router.py
> +router.register('storehouse', StorehouseViewSet, basename='deliverymethod')
Слад, лучше не показывать через API

2023-06-16 13:12 UTC, SaPer663 commented on config/api_router.py
> +router.register('delivery_method', DeliveryMethodViewSet, basename='deliverymethod')
Здесь лучше переименовать в delivery_types

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/views.py
Добавь докстринги!

2023-06-16 13:12 UTC, SaPer663 commented on apps/orders/serializers.py
Добавь докстринги

2023-06-18 13:51 UTC, mikepavlos commented on apps/orders/models.py
> +        validators=[MinValueValidator(limit_value=0, message='Минимальное количество 1!')]
Согласен. Почему бы нельзя, чтоб товара было ноль, если он закончился?

2023-06-22 07:35 UTC, SaPer663 commented on apps/orders/admin.py
> +admin.site.register(Order, OrderAdmin)
Саш, а почему не через декоратор регистрируешь?

2023-06-22 07:35 UTC, SaPer663 commented on apps/orders/models.py
>          Delivery, related_name='order_delivery', verbose_name='Доставка', on_delete=models.SET_NULL, null=True
related_name - название модели, в которой определяется поле, во мн. ч. _orders_

2023-06-22 07:35 UTC, SaPer663 commented on apps/orders/models.py
>      order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ', related_name='order_product')
related_name

2023-06-22 07:35 UTC, SaPer663 commented on apps/orders/models.py
>          Product, on_delete=models.CASCADE, verbose_name='Товар', related_name='product_in_order'
related_name

2023-06-22 07:35 UTC, SaPer663 commented on apps/orders/serializers.py
>      type_delivery = DeliveryTypeSerializer
Не хватает инициализации класса

2023-06-22 07:35 UTC, SaPer663 commented on apps/orders/serializers.py
> +        return data
Это проще сделать через extra_kwargs = {"address": {"required": True}}

2023-06-22 07:35 UTC, SaPer663 commented on apps/orders/serializers.py
>      id = serializers.IntegerField(write_only=True)
Это id чего?
Заказа, продукта или записи в таблице?

2023-06-22 07:35 UTC, SaPer663 commented on apps/orders/serializers.py
> +            raise ValidationError('Эта доставка уже используется')
Вот это не понял, что проверяется здесь?

2023-06-22 19:13 UTC, KoshelevAleksandr commented on apps/orders/serializers.py
>      id = serializers.IntegerField(write_only=True)
id продукта

2023-06-22 19:22 UTC, KoshelevAleksandr commented on apps/orders/serializers.py
> +            raise ValidationError('Эта доставка уже используется')
занят ли экземпляр доставки

2023-06-22 19:25 UTC, KoshelevAleksandr commented on apps/orders/serializers.py
>      type_delivery = DeliveryTypeSerializer
расшифруй пожалуйста, не понял

2023-06-23 12:05 UTC, SaPer663 commented on apps/orders/serializers.py
>      type_delivery = DeliveryTypeSerializer
У тебя здесь только определение DeliveryTypeSerializer, а нужна ещё инициализация DeliveryTypeSerializer()

2023-06-23 12:08 UTC, SaPer663 commented on apps/orders/serializers.py
> +            raise ValidationError('Эта доставка уже используется')
А что значит занят?

2023-06-23 12:35 UTC, SaPer663 commented on apps/orders/serializers.py
> +            raise ValidationError('Эта доставка уже используется')
Что нужно сделать, чтобы сделать заказ, что указать в доставке?

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/models.py
> +    # TODO поле user
User вроде уже готов

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/models.py
> +        DeliveryMethod, related_name='delivery', verbose_name='Доставка', on_delete=models.PROTECT
У меня возник вопрос, для чего мы используем отдельную таблицу способа доставки с одним-единственным полем? Не проще ли тут и указать тип доставки, для чего тут нормализация? Или, судя по комментарию Саши, это необходимо именно для каскадного удаления доставки в случае удаления одного из способов? Это я так, чтоб разобраться)

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/models.py
> +    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар', related_name='order_item')
related_name как правило лучше называть по имени модели, к которой назначена обратная связь, и во множественном числе, потому что по нему извлекаются все существующие у экземпляра объекты по этой модели

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/models.py
> +        return f'{self.adres}'
Нужна ли тут f-строка...
Прошу прощения за занудство))

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/serializers.py
> +        products = value
Попробую пояснить: validate_products - это валидация поля products, в нее аргументом летит его значение (value). Поэтому и так по коду понятно, что value - это значение этого поля products, и нет смысла снова его переименовать.

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/serializers.py
>      type_delivery = DeliveryTypeSerializer
Чтобы заработала функция или класс (вернулось значение или создался экземпляр), их надо вызвать, используя скобки.
`a = func()` # `a` ссылается на возвращенный результат
`a = func` # `a` ссылается на объект функции, т.е. `а` теперь сама функция и теперь `a()` == `func()`
и можно сделать так: `b = a()`

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/serializers.py
>      id = serializers.IntegerField(write_only=True)
Скорей, id записи в таблице, потому что это поле модельного сериализатора от модели `OrderProduct` (в Meta: стоит). В этой таблице идут поля как минимум | `id` | id_product | id_order | quantity |

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/models.py
> +        Delivery, related_name='orders_delivery', verbose_name='Доставка', on_delete=models.SET_NULL, null=True
Вообще, если поле имеет связь `один-к-одному`, то объект имеет только один связанный объект (в единственном числе получается). Джанго автоматом ставит название related_name именем модели, откуда она идет, в нижнем регистре - `order`. И зачастую его нет необходимости указывать явно, потому что по умолчанию, чтобы обратиться к доставке конкретного заказа, указывается конструкция `order.delivery`, и так все понятно).

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/models.py
> +        DeliveryType, related_name='delivery', verbose_name='Доставка', on_delete=models.SET_DEFAULT, default=1
Я боюсь, если типа доставки с `id=1` не существует, то может все упасть. Например, 1 - курьерная у нас была, а потом мы ее удалили, осталась только доставка 2 - до пункта выдачи. Курьеры кончились, доставку по каким-то причинам удалили, остался только `id=2`. Потом мы снова решили добавить курьерную - у нее уже будет `id=3`, и так далее, первый айдишник необязательно под номером 1.

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/models.py
> +        return f'Order {self.id}'
`Order 14` не очень информативно. Полагаю, лучше будет, если заказ отображался примерно так: `Заказ 14, vasya@mail.com`

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/models.py
> +        # order = OrderProduct.objects.annotate(total_price=Sum(F('cost'))).get(order=self)
Если актуально, подскажу. 
Тут нужно вычислить общую стоимость всех товаров заказа. Эта строчка берет все записи заказов с продуктами, составляет список заказов с суммами стоимостей и потом берет один наш заказ с вычисленной стоимостью. Сложновато.
Можно упростить вычисление, взяв сразу товары нашего заказа через related_name и аггрегировать сумму стоимостей этих продуктов.  Заказ - это экземпляр, `self`. Все его товары self.<related_name> (обращается к OrderProduct). Итог, что-то вроде этого: total_cost = self.<related_name>.aggregate(Sum('cost'))

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/models.py
> +    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ', related_name='orders_product')
А вот здесь тот самый `related_name` (смотри коммент выше). Согласись, читабельней, если обращаться `order.products` или `self.products`, чем order.orders_product

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/models.py
> +        Product, on_delete=models.CASCADE, verbose_name='Товар', related_name='products_in_order'
Здесь то же самой про related_name, только наоборот: если мы хотим получить все заказы конкретного продукта, то удобно написать в коде `product.orders`. Сравни с `product.products_in_order`. И самому потом понятней разбираться, что за что в ответе))

2023-06-24 14:38 UTC, mikepavlos commented on apps/orders/models.py
> +
get_price разве не нужно тоже вычислить? Тогда, если не ошибаюсь, отпадет необходимость в переопределении следующего метода save?

2023-06-24 14:43 UTC, mikepavlos requested changes
Ревью по моделям

2023-06-26 18:42 UTC, KoshelevAleksandr commented on apps/orders/models.py
> +        DeliveryMethod, related_name='delivery', verbose_name='Доставка', on_delete=models.PROTECT
Выбор способа будет делаться из уже имеющихся в этой таблице. Мы сможем в любой момента без труда добавить или удалить нужный нам тип доставки через админку и изменения автоматически будут видны на сайте.

2023-06-28 15:35 UTC, SaPer663 approved these changes

2023-06-28 16:11 UTC, mikepavlos approved these changes

2023-06-28 16:11 UTC, mikepavlos commented on apps/orders/models.py
> +        DeliveryType, related_name='delivery', verbose_name='Доставка', on_delete=models.SET_DEFAULT, default=1
Саш, все ломается, когда я в админке удаляю способ доставки с id ключом  '1'.

2023-06-28 16:41 UTC, merged